substitutions:
  dev_name: acw02-salon
  dev_friendly: ACW02 salon
  lang: "en"
  api_encrypted_key: "D2oldc0VP++fni6src89tCSC0UwBhNPgyc8vgYN8/mA="
  ota_password: "REPLACE_WITH_YOUR_PASSWORD"
  ap_password: "fallbackpassword"
  web_server_username: admin
  web_server_password: admin
  board: esp32dev

esphome:
  name: ${dev_name}
  friendly_name: ${dev_friendly}
  platformio_options:
    build_flags:
      - -DDLOCALE_LANG=\"${lang}\"
      - -DDBOARD=\"${board}\"

esp32:
  board: ${board}

web_server:
  port: 80
  auth:
    username: ${web_server_username}
    password: ${web_server_password}
  version: 3
  local : true
  include_internal: true

logger:
  level: INFO
  
api:
  encryption:
    key: ${api_encrypted_key}
  reboot_timeout: 0s #in test for not forcing using esphome native

ota:
  - platform: esphome
    password: ${ota_password}
  - platform: web_server

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  # networks:
  #   - ssid: !secret wifi_ssid
  #     password: !secret wifi_password
  #   - ssid: !secret wifi_ssid2
  #     password: !secret wifi_password2
  #   - ssid: !secret wifi_ssid3
  #     password: !secret wifi_password2
  ap:
    ssid: ${dev_friendly}
    password: ${ap_password}

mqtt:
  broker: "" 
  username: ""
  password: ""
  enable_on_boot: false
  discovery: false
  topic_prefix: ${dev_name}
  birth_message:
    topic: ${dev_name}/status
    payload: online

  will_message:
    topic: ${dev_name}/status
    payload: offline

captive_portal:

uart:
  id: uart_acw02
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  stop_bits: 1

external_components:
  - source:
      type: local
      path: components

packages:
  acw02_entities: !include components/acw02/acw02_en.yaml
  
acw02:
  id: ac_ctrl
  uart_id: uart_acw02
